// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebScrapper.Scraping.ScrappingFluggerDk.DB;

namespace WebScrapper.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20210310003528_Continuation")]
    partial class Continuation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2");

            modelBuilder.Entity("WebScrapper.Scraping.DTO.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathToImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WebsiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("WebsiteId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("WebScrapper.Scraping.DTO.ProductType", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductTypeId");

                    b.HasIndex("Type");

                    b.ToTable("ProductType");
                });

            modelBuilder.Entity("WebScrapper.Scraping.DTO.Website", b =>
                {
                    b.Property<int>("WebsiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("WebsiteId");

                    b.HasIndex("Name");

                    b.ToTable("Website");
                });

            modelBuilder.Entity("WebScrapper.Scraping.DTO.Product", b =>
                {
                    b.HasOne("WebScrapper.Scraping.DTO.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId");

                    b.HasOne("WebScrapper.Scraping.DTO.Website", "Website")
                        .WithMany()
                        .HasForeignKey("WebsiteId");

                    b.Navigation("ProductType");

                    b.Navigation("Website");
                });
#pragma warning restore 612, 618
        }
    }
}
